using System;
using System.Collections.Generic;

namespace MSS_AspDotNetToAndroid_WebApi_WS.Models
{
    public partial class gw_trnsct
    {
        public string idTransaction { get; set; }
        public string EtatTransaction { get; set; }
        public string EtatTransaction2 { get; set; }
        public string EtatCloture { get; set; }
        public string IdCloture { get; set; }
        public string SentTransaction { get; set; }
        public string ReceivedTransaction { get; set; }
        public string CancelReceivedTransaction { get; set; }
        public string IdMerchant { get; set; }
        public string IdMagasin { get; set; }
        public string IdTerminalMerchant { get; set; }
        public string IdTerminal { get; set; }
        public string IMEI { get; set; }
        public string CurrentDate { get; set; }
        public string CurrentTime { get; set; }
        public string CurrentDateTimeTPE { get; set; }
        public string Transactiontype { get; set; }
        public string TransactionSupport { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseCodeAnnulation { get; set; }
        public string InvoiceNumber { get; set; }
        public double? Amount { get; set; }
        public string IdHost { get; set; }
        public string HostRoutage { get; set; }
        public string AnnulationHostRoutage { get; set; }
        public string BinaryVersion { get; set; }
        public string ConfVersion { get; set; }
        public string BankOfRequest { get; set; }
        public string MerchantType { get; set; }
        public string Track2EquivalentData { get; set; }
        public string ApplicationPrimaryAccountNumber { get; set; }
        public string CodeStatus { get; set; }
        public string FID_F_ApprovalCode { get; set; }
        public string DateSystemTransaction { get; set; }
        public string TimeSystemTransaction { get; set; }
        public string TransactionAutorization { get; set; }
        public string Detail { get; set; }
        public string CurrentDateAnnulation { get; set; }
        public string CurrentTimeAnnulation { get; set; }
        public string DateSystemTransactionAnnulation { get; set; }
        public string TimeSystemTransactionAnnulation { get; set; }
        public string AccountType { get; set; }
        public string AcquirerIdentifier { get; set; }
        public string AdditionalTerminalCapabilities { get; set; }
        public string AmountAuthorisedBinary { get; set; }
        public string AmountAuthorisedNumeric { get; set; }
        public string AmountOtherBinary { get; set; }
        public string AmountOtherNumeric { get; set; }
        public string AmountReferenceCurrency { get; set; }
        public string ApplicationCryptogram { get; set; }
        public string ApplicationCurrencyCode { get; set; }
        public string ApplicationCurrencyExponent { get; set; }
        public string ApplicationDiscretionaryData { get; set; }
        public string ApplicationEffectiveDate { get; set; }
        public string ApplicationExpirationDate { get; set; }
        public string ApplicationFileLocator { get; set; }
        public string ApplicationIdentifierCard { get; set; }
        public string ApplicationIdentifierTerminal { get; set; }
        public string ApplicationInterchangeProfile { get; set; }
        public string ApplicationLabel { get; set; }
        public string ApplicationPreferredName { get; set; }
        public string ApplicationPrimaryAccountNumberSequenceNumber { get; set; }
        public string ApplicationPriorityIndicator { get; set; }
        public string ApplicationReferenceCurrency { get; set; }
        public string ApplicationReferenceCurrencyExponent { get; set; }
        public string ApplicationTemplate { get; set; }
        public string ApplicationTransactionCounter { get; set; }
        public string ApplicationUsageControl { get; set; }
        public string CardApplicationVersionNumber { get; set; }
        public string TerminalApplicationVersionNumber { get; set; }
        public string AuthorisationCode { get; set; }
        public string AuthorisationResponseCode { get; set; }
        public string AuthorisationResponseCryptogram { get; set; }
        public string BankIdentifierCode { get; set; }
        public string CardRiskManagementDataObjectList1 { get; set; }
        public string CardRiskManagementDataObjectList2 { get; set; }
        public string CardStatusUpdate { get; set; }
        public string CardholderName { get; set; }
        public string CardholderNameExtended { get; set; }
        public string CardholderVerificationMethodList { get; set; }
        public string CardholderVerificationMethodResults { get; set; }
        public string CardCertificationAuthorityPublicKeyIndex { get; set; }
        public string TerminalCertificationAuthorityPublicKeyIndex { get; set; }
        public string CommandTemplate { get; set; }
        public string CryptogramInformationData { get; set; }
        public string DataAuthenticationCode { get; set; }
        public string DedicatedFileName { get; set; }
        public string DirectoryDefinitionFileName { get; set; }
        public string DirectoryDiscretionaryTemplate { get; set; }
        public string DynamicDataAuthenticationDataObjectList { get; set; }
        public string FileControlInformationIssuerDiscretionaryData { get; set; }
        public string FileControlInformationProprietaryTemplate { get; set; }
        public string FileControlInformationTemplate { get; set; }
        public string ICCDynamicNumber { get; set; }
        public string IntegratedCircuitCardPINEnciphermentPublicKeyCertificate { get; set; }
        public string IntegratedCircuitCardPINEnciphermentPublicKeyExponent { get; set; }
        public string IntegratedCircuitCardPINEnciphermentPublicKeyRemainder { get; set; }
        public byte[] IntegratedCircuitCardPublicKeyCertificate { get; set; }
        public string IntegratedCircuitCardPublicKeyExponent { get; set; }
        public string IntegratedCircuitCardPublicKeyRemainder { get; set; }
        public string InterfaceDeviceSerialNumber { get; set; }
        public string InternationalBankAccountNumber { get; set; }
        public string IssuerActionCodeDefault { get; set; }
        public string IssuerActionCodeDenial { get; set; }
        public string IssuerActionCodeOnline { get; set; }
        public string IssuerApplicationData { get; set; }
        public string IssuerAuthenticationData { get; set; }
        public string IssuerCodeTableIndex { get; set; }
        public string IssuerCountryCode { get; set; }
        public string IssuerCountryCode2 { get; set; }
        public string IssuerCountryCode3 { get; set; }
        public string IssuerIdentificationNumber { get; set; }
        public string IssuerPublicKeyCertificate { get; set; }
        public string IssuerPublicKeyExponent { get; set; }
        public string IssuerPublicKeyRemainder { get; set; }
        public string IssuerScriptCommand { get; set; }
        public string IssuerScriptIdentifier { get; set; }
        public string IssuerScriptTemplate1 { get; set; }
        public string IssuerScriptTemplate2 { get; set; }
        public string IssuerURL { get; set; }
        public string LanguagePreference { get; set; }
        public string LastOnlineApplicationTransactionCounterRegister { get; set; }
        public string LogEntry { get; set; }
        public string LogFormat { get; set; }
        public string LowerConsecutiveOfflineLimit { get; set; }
        public string MerchantCategoryCode { get; set; }
        public string MerchantIdentifier { get; set; }
        public string MerchantNameandLocation { get; set; }
        public string PersonalIdentificationNumberTryCounter { get; set; }
        public string PointofServiceEntryMode { get; set; }
        public string ProcessingOptionsDataObjectList { get; set; }
        public string READRECORDResponseMessageTemplate { get; set; }
        public string ResponseMessageTemplateFormat1 { get; set; }
        public string ResponseMessageTemplateFormat2 { get; set; }
        public string ServiceCode { get; set; }
        public string ShortFileIdentifier { get; set; }
        public string SignedDynamicApplicationData { get; set; }
        public string SignedStaticApplicationData { get; set; }
        public string StaticDataAuthenticationTagList { get; set; }
        public string TerminalActionCodeDefault { get; set; }
        public string TerminalActionCodeDenial { get; set; }
        public string TerminalActionCodeOnline { get; set; }
        public string TerminalCapabilities { get; set; }
        public string TerminalCountryCode { get; set; }
        public string TerminalFloorLimit { get; set; }
        public string TerminalIdentification { get; set; }
        public string TerminalRiskManagementData { get; set; }
        public string TerminalType { get; set; }
        public string TerminalVerificationResults { get; set; }
        public string Track1DiscretionaryData { get; set; }
        public string Track2DiscretionaryData { get; set; }
        public string TransactionCertificateDataObjectList { get; set; }
        public string TransactionCertificateHashValue { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyExponent { get; set; }
        public string TransactionDate { get; set; }
        public string TransactionPersonalIdentificationNumberData { get; set; }
        public string TransactionReferenceCurrencyCode { get; set; }
        public string TransactionReferenceCurrencyExponent { get; set; }
        public string TransactionSequenceCounter { get; set; }
        public string TransactionStatusInformation { get; set; }
        public string TransactionTime { get; set; }
        public string TransactionTypeEmv { get; set; }
        public string UnpredictableNumber { get; set; }
        public string UpperConsecutiveOfflineLimit { get; set; }
        public string EncryptedPIN { get; set; }
        public string PEKVersionNumber { get; set; }
        public string CardBin { get; set; }
        public string CardMask { get; set; }
        public virtual gw_close_day gw_close_day { get; set; }
    }
}
