using MSS_AspDotNetToAndroid_WebApi_WS.Infrastructure;
using MSS_AspDotNetToAndroid_WebApi_WS.Models;
using MSS_AspDotNetToAndroid_WebApi_WS.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace MSS_AspDotNetToAndroid_WebApi_WS.Utils.UserVerificationCodeUtils
{
    public class UserVerificationCodeManager
    {
        private static IDatabaseFactory dbf = new DatabaseFactory();
        private static IUnitOfWork uow = new UnitOfWork(dbf);

        UserVerificationCodeRepository _userVerificationCodeRepos;

        public UserVerificationCodeManager()
        {
            _userVerificationCodeRepos = new UserVerificationCodeRepository();
        }

        public void CreateVerificationCode(UserVerificationCode uvc)
        {
            _userVerificationCodeRepos.AddNewVerificationCode(uvc);
        }

        public string GetLastVerificationCodeByIdUser(string idUser)
        {
            var verifCode = _userVerificationCodeRepos.getTheLastVerificationCodeByIdUser(idUser);
            return verifCode;
        }

        public string VerificationCode_ResetPassword_RadomGenerator(int length)
        {
            var list_AllVerifCodes = _userVerificationCodeRepos.getAllVerificationCodes();
            var list_verifCodesAttribute = list_AllVerifCodes.Select(vc => vc.VerificationCode).ToList();

            Random random = new Random();
            const string pool = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_+";
            var builder = new StringBuilder();

            for (var i = 0; i < length; i++)
            {
                var c = pool[random.Next(0, pool.Length)];
                builder.Append(c);
            }

            string autoGeneratedVerifCode = builder.ToString();
            string GeneratedVerifCode = " ";

            for (int i = 0; i < list_verifCodesAttribute.Count; i++)
            {
                if (!autoGeneratedVerifCode.Equals(list_verifCodesAttribute[i]))
                {
                    GeneratedVerifCode = autoGeneratedVerifCode;
                }
                else
                {
                    GeneratedVerifCode = null;
                }
            }
             
            return GeneratedVerifCode;
        }

    }
}